# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cc154486ec184075f79ffb4e117563124f9e3f716990863675652b06e9104be777ca2a5017698c9e0bc7733a7050e39b813dacbd80c5b91c19564b1550c01e

test:
  secret_key_base: 21a09457839fd2320145705f0dfa5dd4f4e15d94569da8b24345148a2c98cd490b1d5a88c41ce9c2f8466f10d39e46d15b89cd1339982513384db4d537f08014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
